"use strict";
const $ = (id) => document.getElementById(id);
const labels = {state:"状态",decision:"决策",outcome:"结果",failure:"陷阱",heuristic:"启发式",procedure:"流程",evaluator:"评估器",artifact:"产物"};
const statuses = {candidate:"候选 · 仍需验证",active:"有外部证据",disputed:"存在争议 · 需检查",superseded:"已被新经验替代",archived:"已归档",rejected:"已拒绝",quarantined:"来源指令已隔离"};
const scopes = {task:"任务",project:"项目",domain:"跨项目",personal:"个人"};
const state = {overview:null,project:"",type:"",view:"experiences",detail:null,compiled:"",searchTimer:null,toastTimer:null};
function element(tag, className, text) { const node = document.createElement(tag); if(className)node.className=className; if(text!==undefined)node.textContent=text; return node; }
function basename(path) { return String(path).split(/[\\/]/).filter(Boolean).pop() || "跨项目模式"; }
function date(value) { return new Date(value).toLocaleString("zh-CN",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}); }
function toast(message,error=false) { clearTimeout(state.toastTimer); $("toast").textContent=message; $("toast").classList.toggle("error",error); $("toast").hidden=false; state.toastTimer=setTimeout(()=>{$("toast").hidden=true;},4500); }
async function api(path,body) { const options = body===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json","X-PEL-Request":"1"},body:JSON.stringify(body)}; const response=await fetch(path,options); const data=await response.json(); if(!response.ok)throw new Error(data.error||"请求失败"); return data; }
async function busy(button,work) { button.disabled=true; try{return await work();}catch(error){toast(error.message,true);}finally{button.disabled=false;} }
function typeBadge(type) { return element("span","type-badge "+type,"◈ "+(labels[type]||type)); }
function rebuildProjects() {
  const projects=state.overview.projects; $("project-nav").replaceChildren();
  for(const path of ["",...projects]) { const button=element("button","project-link"+(state.project===path?" active":"")); button.append(element("span","",path?"▧":"◈"),element("div","",path?basename(path):"所有项目"));button.title=path||"包含跨项目候选经验";button.addEventListener("click",()=>{state.project=path;rebuildProjects();switchView("experiences");loadExperiences().catch(e=>toast(e.message,true));});$("project-nav").append(button); }
  $("projects-list").replaceChildren(...projects.map(path=>{const option=element("option");option.value=path;return option;}));
  $("domains-list").replaceChildren(...state.overview.domains.map(domain=>{const option=element("option");option.value=domain;return option;}));
  if(!$("compile-project").value)$("compile-project").value=projects[0]||state.overview.default_project;
}
async function refresh() { state.overview=await api("/api/overview"); const data=state.overview; $("metric-total").textContent=data.experiences;$("metric-episodes").textContent=data.episodes;$("metric-generalized").textContent=data.generalizations;$("metric-candidates").textContent=data.candidates;$("nav-count").textContent=data.experiences;$("audit-status").textContent=data.audit.valid?"✓ 生命周期记录校验通过":"生命周期记录校验异常";document.querySelector(".offline-badge").textContent=data.demo_episodes===data.episodes&&data.episodes?"合成演示 · 离线提取":"离线提取"; rebuildProjects(); await loadExperiences(); if(state.view==="episodes")await loadEpisodes(); }
async function loadExperiences() {
  const query=new URLSearchParams({q:$("search").value,type:state.type,status:$("status-filter").value,project:state.project});
  const items=await api("/api/experiences?"+query); $("experience-grid").replaceChildren();$("experience-count").textContent=items.length;
  for(const item of items) { const card=element("button","experience-card");card.setAttribute("aria-label",(labels[item.type]||item.type)+"："+item.statement);const top=element("div","card-top");top.append(typeBadge(item.type),element("span","card-scope",(item.pinned?"⌖ ":"")+scopes[item.scope]));const footer=element("div","card-footer");footer.append(element("span","card-project",item.project?basename(item.project):item.domain),element("span","evidence-count","↳ "+item.evidence_ids.length+" 条证据"));card.append(top,element("p","card-statement",item.statement),element("div","card-status "+item.lifecycle_state,statuses[item.lifecycle_state]),footer);card.addEventListener("click",()=>openDetail(item.id));$("experience-grid").append(card); }
  $("empty-state").hidden=items.length>0;
  if(!items.length&&state.overview.experiences){$("empty-state").querySelector("h3").textContent="没有符合条件的经验";$("empty-state").querySelector("p").textContent="试着调整类型、状态、项目或搜索词。";$("empty-demo").hidden=true;}else{$("empty-state").querySelector("h3").textContent="经验，从一次工作开始。";$("empty-state").querySelector("p").textContent="接入 Codex 或 Claude Code 会话，自动提取值得保留的经验。也可以加载演示，探索完整的经验生命周期。";$("empty-demo").hidden=false;}
}
const headings={experiences:["经验库","每一次工作，都成为下一次的经验。","从尝试、决策和结果中积累经验，为未来的代理提供恰当的上下文。"],episodes:["工作片段","保留过程，才能复用经验。","代理可以不同，工作过程与证据保持连续。"],compiler:["上下文编译","让下一次任务，从已有经验出发。","检索相关经验，编译成适合当前任务的简报、流程或评估参考。"]};
function switchView(view) {state.view=view;for(const name of Object.keys(headings))$(name+"-view").hidden=name!==view;document.querySelectorAll("button[data-view]").forEach(button=>button.classList.toggle("selected",button.dataset.view===view));const [breadcrumb,title,description]=headings[view];$("breadcrumb").textContent=breadcrumb;$("page-title").textContent=title;$("page-description").textContent=description;if(view==="episodes")loadEpisodes().catch(e=>toast(e.message,true));}
async function loadEpisodes() {const items=await api("/api/episodes");$("episode-list").replaceChildren();for(const item of items){const card=element("article","episode-card");const heading=element("div","episode-heading");heading.append(element("span","",item.source==="codex"?"CODEX":item.source==="claude"?"CLAUDE CODE":"EPISODE"),element("time","",date(item.last_observed_at)));const meta=element("div","episode-meta");meta.append(element("span","","▧ "+basename(item.project)),element("span","",item.domain||"未指定领域"),element("span","",item.event_count+" 条标准化事件"));card.append(heading,element("h3","",item.objective),meta);$("episode-list").append(card);}if(!items.length)$("episode-list").append(element("p","form-note","尚无工作片段。接入一个会话或加载演示。"));}
async function openDetail(id) {try{const data=await api("/api/experiences/"+id);state.detail=data.experience;renderDetail(data);if(!$("detail-dialog").open)$("detail-dialog").showModal();}catch(e){toast(e.message,true);}}
function renderDetail(data) {
  const item=data.experience;const container=$("detail-content");container.replaceChildren(typeBadge(item.type),element("h2","detail-statement",item.statement));const tags=element("div","detail-tags");tags.append(element("span","",statuses[item.lifecycle_state]),element("span","","置信度 "+item.confidence.toFixed(2)),element("span","",scopes[item.scope]+"范围"),element("span","",item.evidence_ids.length+" 条证据"));container.append(tags);
  for(const [name,ids]of [["替代了",item.supersedes],["存在冲突",item.contradicted_by],["归纳自",item.generalizes]]){if(ids.length){const note=element("div","relation-note",name+"：");for(const id of ids){const button=element("button","text-button",id);button.addEventListener("click",()=>openDetail(id));note.append(button,document.createTextNode(" "));}container.append(note);}}
  const evidenceSection=element("section","detail-section");evidenceSection.append(element("h3","","来源与证据"));for(const evidence of data.evidence){const block=element("article","evidence-item");const title=element("div","evidence-title");title.append(element("strong","",evidence.kind),element("span","",date(evidence.observed_at)));block.append(title,element("div","evidence-source",evidence.source_uri+":"+evidence.line),element("pre","",evidence.snippet));evidenceSection.append(block);}container.append(evidenceSection);
  const timeline=element("section","detail-section");timeline.append(element("h3","","生命周期"));const list=element("div","timeline");for(const event of data.history){const row=element("div","timeline-item");const content=element("div");content.append(element("strong","",event.action),document.createTextNode(" · "+date(event.at)),element("pre","",JSON.stringify(event.details,null,2)));row.append(element("span","timeline-marker"),content);list.append(row);}timeline.append(list);container.append(timeline);
  $("feedback-form").reset();$("correction-field").hidden=true;$("narrow-fields").hidden=true;$("correction-input").required=false;$("narrow-key").required=false;
}
$("feedback-action").addEventListener("change",()=>{const action=$("feedback-action").value;$("correction-field").hidden=action!=="correct";$("narrow-fields").hidden=action!=="narrow";$("correction-input").required=action==="correct";$("narrow-key").required=action==="narrow";});
$("feedback-form").addEventListener("submit",event=>{event.preventDefault();busy(event.submitter,async()=>{const result=await api("/api/feedback",{id:state.detail.id,action:$("feedback-action").value,reason:$("feedback-reason").value,statement:$("correction-input").value,scope:$("narrow-scope").value,scope_key:$("narrow-key").value});await refresh();await openDetail(result.id);toast("反馈已保存，经验与依赖它的归纳已更新。");});});
$("compiler-form").addEventListener("submit",event=>{event.preventDefault();busy(event.submitter,async()=>{const result=await api("/api/compile",{task:$("task-input").value,project:$("compile-project").value,domain:$("compile-domain").value,agent:$("compile-agent").value,format:$("compile-format").value,budget_tokens:Number($("compile-budget").value),phase:$("compile-phase").value,task_id:$("compile-task-id").value});state.compiled=result.text;$("context-text").textContent=result.text;$("output-meta").textContent=result.selected_ids.length+" 条经验 · 保守 token 上界 "+result.used_tokens_upper_bound+" / "+result.context.budget_tokens+" · "+result.omitted_count+" 条因预算省略";$("copy-context").disabled=false;});});
$("copy-context").addEventListener("click",()=>busy($("copy-context"),async()=>{await navigator.clipboard.writeText(state.compiled);toast("已复制代理上下文。");}));
$("import-button").addEventListener("click",()=>{$("import-form").reset();$("file-label").textContent="Codex · Claude Code · 标准化 Episode";$("import-result").textContent="";$("import-dialog").showModal();});
$("import-file").addEventListener("change",()=>{$("file-label").textContent=$("import-file").files[0]?.name||"Codex · Claude Code · 标准化 Episode";});
$("import-form").addEventListener("submit",event=>{event.preventDefault();busy(event.submitter,async()=>{const file=$("import-file").files[0];if(!file)throw new Error("请选择会话文件");if(file.size>3*1024*1024)throw new Error("界面导入上限为 3 MiB；更大的会话请使用 CLI。");const result=await api("/api/ingest",{content:await file.text(),filename:file.name,source:$("import-source").value,domain:$("import-domain").value,project:$("import-project").value});await refresh();$("import-dialog").close();toast(result.unchanged?"该会话已接入，经验保持不变。":"已保存 "+result.created+" 条新经验，合并 "+result.merged+" 条。");});});
async function loadDemo(button){return busy(button,async()=>{const result=await api("/api/demo",{});state.project="";await refresh();$("task-input").value=result.next_task.task;$("compile-project").value=result.next_task.project;$("compile-domain").value=result.next_task.domain;toast("已加载三个领域的合成演示；模拟闭环通过。");});}
$("demo-button").addEventListener("click",()=>loadDemo($("demo-button")));$("empty-demo").addEventListener("click",()=>loadDemo($("empty-demo")));
document.querySelectorAll("button[data-view]").forEach(button=>button.addEventListener("click",()=>switchView(button.dataset.view)));
document.querySelectorAll(".close-dialog").forEach(button=>button.addEventListener("click",()=>button.closest("dialog").close()));
for(const type of ["",...Object.keys(labels)]){const chip=element("button","filter-chip"+(type===""?" active":""),type?labels[type]:"全部");chip.addEventListener("click",()=>{state.type=type;$("type-filters").querySelectorAll("button").forEach(b=>b.classList.toggle("active",b===chip));loadExperiences().catch(e=>toast(e.message,true));});$("type-filters").append(chip);}
$("status-filter").addEventListener("change",()=>loadExperiences().catch(e=>toast(e.message,true)));$("search").addEventListener("input",()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>loadExperiences().catch(e=>toast(e.message,true)),180);});
document.addEventListener("keydown",event=>{if(event.key==="/"&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)&&!document.querySelector("dialog[open]")){event.preventDefault();switchView("experiences");$("search").focus();}});
refresh().catch(e=>toast(e.message,true));
